# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ develop, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        default: develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
#  slask:
#    runs-on: ubuntu-latest
#    steps:
#      - shell: bash
#        run: |
#          echo "Hello ${{ secrets.OSSRH_USERNAME }}"
#          echo "World ${{ secrets.OSSRH_PASSWORD }}"
  build:
    uses: bjuvensjo/.github/.github/workflows/maven-ci.yml@main
    with:
      pom: ./rsimulator-pom-modules/pom.xml
      version: '["11"]'
      
      
      
