# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on:
  push:
    branches: [ develop, master, develop2, master2 ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
        default: develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    uses: bjuvensjo/.github/.github/workflows/maven-ci.yml@main
    with:
      command: cd rsimulator-pom-parent && mvn -Dgpg.skip -B package --file pom.xml && cd ../rsimulator-pom-modules && mvn -Dmaven.javadoc.skip=true -Dgpg.skip -fae -B package --file pom.xml
      version: '["11", "17"]'
      
      
      
